[package]

name = "rustation"
version = "0.0.1"
authors = ["Lionel Flandrin <lionel.flandrin@gmail.com>"]
build = "build.rs"

[build-dependencies]
gl_generator = "0.1.0"
khronos_api = "0.0.8"

description = "A PlayStation emulator"
homepage = "https://github.com/simias/rustation"
repository = "https://github.com/simias/rustation"
documentation = "https://github.com/simias/rustation/wiki"
readme = "README.md"
license = "GPL-2.0+"
keywords = ["emulator", "playstation"]

[dependencies]

libc = "0.1.6"
gl_common = "0.1.0"
sdl2 = "0.9.1"
